# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIDc1_tAbRDtiMvOKooBCbhuw8NJS4Tb
"""

from transformers import pipeline
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

class TextInput(BaseModel):
    text: str

@app.post("/summarize")
def summarize(input: TextInput):
    summary = summarizer(input.text, max_length=128, min_length=30, do_sample=False)
    return {"summary": summary[0]["summary_text"]}

